spring:
  application:
    name: fashion-backend
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/fashion_db?options=-c%20timezone=UTC
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080

application:
  security:
    jwt:
      secret-key: NoPEkExKyE9nWtQ+edD8KTTTAc1KZOcQoI7kOI/Gj7Gs= # 256-bit Base64 secret
      expiration: 86400000 # 1 day

  ai:
    openai:
      api-key: ${OPENAI_KEY}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
