spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/fashion_db?options=-c%20timezone=UTC}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
